spring:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost:3306/forohub
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
  port:
    9090
api:
  security:
    secret: 123456
